import type { Metadata } from 'next';
import './globals.css';
import { inter, italianno, old_standard, praise } from '../lib/font';

import { cn } from '@/lib/utils';
import { Navbar } from '@/components/layout/nav-bar';
import { EngageFooter } from '@/components/layout/EngageFooter';

export const metadata: Metadata = {
	title: 'Films by Elijiah',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={cn(
					inter.className,
					praise.variable,
					italianno.variable,
					old_standard.variable
				)}
			>
				<Navbar />
				{children}
				<EngageFooter />
			</body>
		</html>
	);
}
